import db_docu

CODCOLIGADA = [];RA = [];IDPERLET = [];IDHABILITACAOFILIAL = [];CODCONTRATO=[]
CIDADE = [];RG = [];NOMEALUNO = []; UNIDADE = []; SEXO = []; LOCALNASC = []; NOMERESPF = []
ENDERECO = []; CURSO = []; CEP = []; SERIE = []; PERIODO = []; NATURALIDADE = []; DATANASC = []
TELR = []; TELC = []; UF = []; BAIRRO = []; PAI = []; MAE = []; RA_ALUNO = []; CPF = []; CODCONTRATO_ALUNO=[]; ANOLETIVO = []

### ARRAYS ADITIVO ###
BOLSA1 = []; BOLSA2 = []; BOLSA3 = []; BOLSA4 = [];BOLSA5 = []; BOLSA6 = [];BOLSA7 = []; BOLSA8 = [];BOLSA9 = []; BOLSA10 = [];BOLSA11 = []; BOLSA12 = [];BOLSA13 = []
VALB = []; VALB2 = []; VALB3 = []; VALB4 = []; VALB5 = []; VALB6 = []; VALB7 = []; VALB8 = []; VALB9 = []; VALB10 = []; VALB11 = []; VALB12 = []; VALB13 = []
VALDESC1 = []; VALDESC2 = []; VALDESC3 = []; VALDESC4 = []; VALDESC5 = []; VALDESC6 = []; VALDESC7 = []; VALDESC8 = []; VALDESC9 = []; VALDESC10 = []; VALDESC11 = []; VALDESC12 = []; VALDESC13 = []
VALLQ1 = []; VALLQ2 = []; VALLQ3 = []; VALLQ4 = []; VALLQ5 = []; VALLQ6 = []; VALLQ7 = []; VALLQ8 = []; VALLQ9 = []; VALLQ10 = []; VALLQ11 = []; VALLQ12 = []; VALLQ13 = []
RA_AD = [];  IDHABILITACAOFILIAL_AD = []; CODCOLIGADA_AD = []; IDPERLET_AD = []; CODCONTRATO_AD = []; NOME_AD =[]; ANOLETIVO_AD = []; CPF_AD = []; RG_AD = []; RESP_AD = []; UNIDADE_AD = []; CURSO_AD = []

def start_variables_envelope():
    db_docu.select = '''SELECT TOP (5) 
        CT.CODCOLIGADA
    ,	CT.IDHABILITACAOFILIAL
    ,	CT.IDPERLET
    ,	CT.RA
    ,	CT.CODCONTRATO
    FROM
        BD20200619_DSV.DBO.SCONTRATO CT INNER JOIN BD20200619_DSV.dbo.VW_ZZ_ALUNO_CONTRATO VW	ON
                                        CT.CODCOLIGADA			=	VW.CODCOLIGADA
                                    AND CT.IDHABILITACAOFILIAL	=	VW.IDHABILITACAOFILIAL
                                    AND CT.IDPERLET				=	VW.IDPERLET
                                    AND CT.RA					=	VW.RA
                                    AND	CT.CODCONTRATO			=	VW.CODCONTRATO
                                        INNER JOIN BD20200619_DSV.dbo.PPESSOA PP				ON
                                        VW.CODPESSOA			=	PP.CODIGO
                                        INNER JOIN BD20200619_DSV.dbo.FCFO	FC					ON
										FC.CODCFO				=	VW.CODCFO
    WHERE
        CT.IDPERLET				=	'44'
    AND CT.ASSINADO				=	'N'
                        '''
    db_docu.select_sql(db_docu.select)
    for rows in db_docu.rows:
        row = rows.rstrip()
        arrRow = row.split(",")
        CODCOLIGADA.append(arrRow[0])
        RA.append(arrRow[1])
        IDPERLET.append(arrRow[2])
        IDHABILITACAOFILIAL.append(arrRow[3])
        CODCONTRATO.append(arrRow[4])

def start_variables_template():
    db_docu.select = '''SELECT TOP (5) 
    	VW.CIDADE_ALUNO		[CIDADE]
    ,   PP.CARTIDENTIDADE	[RG]
    ,	VW.ALUNO			[NOMEALUNO]
    ,	VW.UNIDADE
    ,	VW.SEXO
    ,	VW.NATURALIDADE		[LOCALNASC]
    ,	VW.RESPFIN			[NOMERESPF]
    ,	FC.RUA + ' '+ FC.NUMERO + ' ' + FC.COMPLEMENTO [ENDERECO]
    ,	VW.NOME_CURSO		[CURSO]
    ,	VW.CEP_ALUNO		[CEP]
    ,	VW.NOME_SERIE		[SEIRE]
    ,	VW.PERIODO
    ,	VW.NATURALIDADE		
    ,	CONVERT(VARCHAR(10),PP.DTNASCIMENTO,103)		[DATANASC]
    ,	VW.RESPFIN_TEL		[TELR]
    ,	VW.TEL1_ALUNO		[TELC]
    ,	VW.ESTADONATAL		[UF]
    ,	VW.BAIRRO_ALUNO		[BAIRRO]
    ,	VW.NOME_PAI			[PAI]
    ,	VW.NOME_MAE			[MAE]
    ,	CT.RA
    ,	VW.RESPFIN_CPF
    ,	CT.CODCONTRATO
    ,	VW.ANO_LETIVO		[ANOLETIVO]
    FROM
        BD20200619_DSV.DBO.SCONTRATO CT INNER JOIN BD20200619_DSV.dbo.VW_ZZ_ALUNO_CONTRATO VW	ON
                                        CT.CODCOLIGADA			=	VW.CODCOLIGADA
                                    AND CT.IDHABILITACAOFILIAL	=	VW.IDHABILITACAOFILIAL
                                    AND CT.IDPERLET				=	VW.IDPERLET
                                    AND CT.RA					=	VW.RA
                                    AND	CT.CODCONTRATO			=	VW.CODCONTRATO
                                        INNER JOIN BD20200619_DSV.dbo.PPESSOA PP				ON
                                        VW.CODPESSOA			=	PP.CODIGO
                                        INNER JOIN BD20200619_DSV.dbo.FCFO	FC					ON
										FC.CODCFO				=	VW.CODCFO
    WHERE
        CT.IDPERLET				=	'44'
    AND CT.ASSINADO				=	'N'
                    '''
    db_docu.select_sql(db_docu.select)
    for rows in db_docu.rows:
        row = rows.rstrip()
        arrRow = row.split(",")
        CIDADE.append(arrRow[0])
        RG.append(arrRow[1])
        NOMEALUNO.append(arrRow[2])
        UNIDADE.append(arrRow[3])
        SEXO.append(arrRow[4])
        LOCALNASC.append(arrRow[5])
        NOMERESPF.append(arrRow[6])
        ENDERECO.append(arrRow[7])
        CURSO.append(arrRow[8])
        CEP.append(arrRow[9])
        SERIE.append(arrRow[10])
        PERIODO.append(arrRow[11])
        NATURALIDADE.append(arrRow[12])
        DATANASC.append(arrRow[13])
        TELR.append(arrRow[14])
        TELC.append(arrRow[15])
        UF.append(arrRow[16])
        BAIRRO.append(arrRow[17])
        PAI.append(arrRow[18])
        MAE.append(arrRow[19])
        RA_ALUNO.append(arrRow[20])
        CPF.append(arrRow[21])
        CODCONTRATO_ALUNO.append(arrRow[22])
        ANOLETIVO.append(arrRow[23])

def start_variables_template_aditivo():
    db_docu.select = '''SELECT DISTINCT
/*  --------------------------------------- VALOR BRUTO --------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST(VALOR.VALOR_PARCELA AS NUMERIC (15,2)) 'VALB'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'1'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALB

/*  --------------------------------------- VALOR BRUTO --------------------------------*/
,	C.RA
,	C.IDHABILITACAOFILIAL
,	C.CODCOLIGADA
,	C.IDPERLET
,	C.CODCONTRATO
,	VALOR.ALUNO
,	VALOR.ANO_LETIVO
,	CT.RESPFIN
,	CT.RESPFIN_CPF
,	CT.RGRESPFIN
,	CT.UNIDADE
,	CT.NOME_CURSO
,	
/*  --------------------------------------- BOLSA 1 --------------------------------*/
ISNULL(
(
SELECT
CONVERT(VARCHAR(MAX),CONVERT(DECIMAL(10,2),SUM(VLBOLSADESCONTO))) + '%' as 'BOLSA'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'1'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--') BOLSA1

/*  --------------------------------------- BOLSA 1 --------------------------------*/

,	
/*  --------------------------------------- BOLSA 2 --------------------------------*/

ISNULL(
(
SELECT
CONVERT(VARCHAR(MAX),CONVERT(DECIMAL(10,2),SUM(VLBOLSADESCONTO))) + '%' as 'BOLSA'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'2'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--') BOLSA2

/*  --------------------------------------- BOLSA 2 --------------------------------*/

,	
/*  --------------------------------------- BOLSA 3 --------------------------------*/

ISNULL(
(
SELECT
CONVERT(VARCHAR(MAX),CONVERT(DECIMAL(10,2),SUM(VLBOLSADESCONTO))) + '%' as 'BOLSA'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'3'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--') BOLSA3

/*  --------------------------------------- BOLSA 3 --------------------------------*/

,	
/*  --------------------------------------- BOLSA 4 --------------------------------*/
ISNULL(
(
SELECT
CONVERT(VARCHAR(MAX),CONVERT(DECIMAL(10,2),SUM(VLBOLSADESCONTO))) + '%' as 'BOLSA'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'4'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--') BOLSA4

/*  --------------------------------------- BOLSA 4 --------------------------------*/

,	
/*  --------------------------------------- BOLSA 5 --------------------------------*/
ISNULL(
(
SELECT
CONVERT(VARCHAR(MAX),CONVERT(DECIMAL(10,2),SUM(VLBOLSADESCONTO))) + '%' as 'BOLSA'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'5'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--') BOLSA5

/*  --------------------------------------- BOLSA 5 --------------------------------*/

,	
/*  --------------------------------------- BOLSA 6 --------------------------------*/
ISNULL(
(
SELECT
CONVERT(VARCHAR(MAX),CONVERT(DECIMAL(10,2),SUM(VLBOLSADESCONTO))) + '%' as 'BOLSA'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'6'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--')BOLSA6

/*  --------------------------------------- BOLSA 6 --------------------------------*/

,	
/*  --------------------------------------- BOLSA 7 --------------------------------*/
ISNULL(
(
SELECT
CONVERT(VARCHAR(MAX),CONVERT(DECIMAL(10,2),SUM(VLBOLSADESCONTO))) + '%' as 'BOLSA'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'7'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--') BOLSA7

/*  --------------------------------------- BOLSA 7 --------------------------------*/

,	
/*  --------------------------------------- BOLSA 8 --------------------------------*/
ISNULL(
(
SELECT
CONVERT(VARCHAR(MAX),CONVERT(DECIMAL(10,2),SUM(VLBOLSADESCONTO))) + '%' as 'BOLSA'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'8'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--') BOLSA8

/*  --------------------------------------- BOLSA 8 --------------------------------*/

,	
/*  --------------------------------------- BOLSA 9 --------------------------------*/
ISNULL(
(
SELECT
CONVERT(VARCHAR(MAX),CONVERT(DECIMAL(10,2),SUM(VLBOLSADESCONTO))) + '%' as 'BOLSA'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'9'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--')BOLSA9

/*  --------------------------------------- BOLSA 9 --------------------------------*/

,	
/*  --------------------------------------- BOLSA 10 --------------------------------*/
ISNULL(
(
SELECT
CONVERT(VARCHAR(MAX),CONVERT(DECIMAL(10,2),SUM(VLBOLSADESCONTO))) + '%' as 'BOLSA'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'10'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--') BOLSA10

/*  --------------------------------------- BOLSA 10 --------------------------------*/

,	
/*  --------------------------------------- BOLSA 11 --------------------------------*/
ISNULL(
(
SELECT
CONVERT(VARCHAR(MAX),CONVERT(DECIMAL(10,2),SUM(VLBOLSADESCONTO))) + '%' as 'BOLSA'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'11'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--')BOLSA11

/*  --------------------------------------- BOLSA 11 --------------------------------*/

,	
/*  --------------------------------------- BOLSA 12 --------------------------------*/
ISNULL(
(
SELECT
CONVERT(VARCHAR(MAX),CONVERT(DECIMAL(10,2),SUM(VLBOLSADESCONTO))) + '%' as 'BOLSA'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'12'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--')BOLSA12

/*  --------------------------------------- BOLSA 12 --------------------------------*/

,	
/*  --------------------------------------- BOLSA 13 --------------------------------*/
ISNULL(
(
SELECT
CONVERT(VARCHAR(MAX),CONVERT(DECIMAL(10,2),SUM(VLBOLSADESCONTO))) + '%' as 'BOLSA'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'13'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--')BOLSA13

/*  --------------------------------------- BOLSA 13 --------------------------------*/

,	
/*  --------------------------------------- DESCONTO 1 --------------------------------*/
ISNULL(
(
SELECT
	CONVERT(VARCHAR(100),CAST(VW.VLDESCONTO AS NUMERIC(15,2))) 'VALOR_DESCONTO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'1'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--') VALDESC1

/*  --------------------------------------- DESCONTO 1 --------------------------------*/

,	
/*  --------------------------------------- DESCONTO 2 --------------------------------*/
ISNULL(
(
SELECT
	CONVERT(VARCHAR(100),CAST(VW.VLDESCONTO AS NUMERIC(15,2))) 'VALOR_DESCONTO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'2'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--') VALDESC2

/*  --------------------------------------- DESCONTO 2 --------------------------------*/

,	
/*  --------------------------------------- DESCONTO 3 --------------------------------*/
ISNULL(
(
SELECT
	CONVERT(VARCHAR(100),CAST(VW.VLDESCONTO AS NUMERIC(15,2))) 'VALOR_DESCONTO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'3'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--') VALDESC3

/*  --------------------------------------- DESCONTO 3 --------------------------------*/

,	
/*  --------------------------------------- DESCONTO 4 --------------------------------*/
ISNULL(
(
SELECT
	CONVERT(VARCHAR(100),CAST(VW.VLDESCONTO AS NUMERIC(15,2))) 'VALOR_DESCONTO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'4'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--') VALDESC4

/*  --------------------------------------- DESCONTO 4 --------------------------------*/

,	
/*  --------------------------------------- DESCONTO 5 --------------------------------*/
ISNULL(
(
SELECT
	CONVERT(VARCHAR(100),CAST(VW.VLDESCONTO AS NUMERIC(15,2))) 'VALOR_DESCONTO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'5'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--') VALDESC5

/*  --------------------------------------- DESCONTO 5 --------------------------------*/

,	
/*  --------------------------------------- DESCONTO 6 --------------------------------*/
ISNULL(
(
SELECT
	CONVERT(VARCHAR(100),CAST(VW.VLDESCONTO AS NUMERIC(15,2))) 'VALOR_DESCONTO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'6'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--') VALDESC6

/*  --------------------------------------- DESCONTO 6 --------------------------------*/

,	
/*  --------------------------------------- DESCONTO 7 --------------------------------*/
ISNULL(
(
SELECT
	CONVERT(VARCHAR(100),CAST(VW.VLDESCONTO AS NUMERIC(15,2))) 'VALOR_DESCONTO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'7'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--') VALDESC7

/*  --------------------------------------- DESCONTO 7 --------------------------------*/

,	
/*  --------------------------------------- DESCONTO 8 --------------------------------*/
ISNULL(
(
SELECT
	CONVERT(VARCHAR(100),CAST(VW.VLDESCONTO AS NUMERIC(15,2))) 'VALOR_DESCONTO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'8'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--') VALDESC8

/*  --------------------------------------- DESCONTO 8 --------------------------------*/

,	
/*  --------------------------------------- DESCONTO 9 --------------------------------*/
ISNULL(
(
SELECT
	CONVERT(VARCHAR(100),CAST(VW.VLDESCONTO AS NUMERIC(15,2))) 'VALOR_DESCONTO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'9'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--') VALDESC9

/*  --------------------------------------- DESCONTO 9 --------------------------------*/

,	
/*  --------------------------------------- DESCONTO 10 --------------------------------*/
ISNULL(
(
SELECT
	CONVERT(VARCHAR(100),CAST(VW.VLDESCONTO AS NUMERIC(15,2))) 'VALOR_DESCONTO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'10'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--') VALDESC10

/*  --------------------------------------- DESCONTO 10 --------------------------------*/

,	
/*  --------------------------------------- DESCONTO 11 --------------------------------*/
ISNULL(
(
SELECT
	CONVERT(VARCHAR(100),CAST(VW.VLDESCONTO AS NUMERIC(15,2))) 'VALOR_DESCONTO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'11'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--') VALDESC11

/*  --------------------------------------- DESCONTO 11 --------------------------------*/

,	
/*  --------------------------------------- DESCONTO 12 --------------------------------*/
ISNULL(
(
SELECT
	CONVERT(VARCHAR(100),CAST(VW.VLDESCONTO AS NUMERIC(15,2))) 'VALOR_DESCONTO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'12'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--') VALDESC12

/*  --------------------------------------- DESCONTO 12 --------------------------------*/

,	
/*  --------------------------------------- DESCONTO 13 --------------------------------*/
ISNULL(
(
SELECT
	CONVERT(VARCHAR(100),CAST(VW.VLDESCONTO AS NUMERIC(15,2))) 'VALOR_DESCONTO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'13'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
),'--X--X--') VALDESC13

/*  --------------------------------------- DESCONTO 13 --------------------------------*/

,	
/*  --------------------------------------- VALOR LIQUIDO 1 --------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST((MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) - ( MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) * 
	CAST(SUM(CAST(VLBOLSADESCONTO AS NUMERIC (15,2))/100) AS NUMERIC (15,2)))) AS NUMERIC (15,2)) 'VALOR_LIQUIDO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'1'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALLQ1

/*  --------------------------------------- VALOR LIQUIDO 1 --------------------------------*/

,	
/*  --------------------------------------- VALOR LIQUIDO 2 --------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST((MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) - ( MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) * 
	CAST(SUM(CAST(VLBOLSADESCONTO AS NUMERIC (15,2))/100) AS NUMERIC (15,2)))) AS NUMERIC (15,2)) 'VALOR_LIQUIDO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'2'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALLQ2

/*  --------------------------------------- VALOR LIQUIDO 2 --------------------------------*/

,	
/*  --------------------------------------- VALOR LIQUIDO 3 --------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST((MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) - ( MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) * 
	CAST(SUM(CAST(VLBOLSADESCONTO AS NUMERIC (15,2))/100) AS NUMERIC (15,2)))) AS NUMERIC (15,2)) 'VALOR_LIQUIDO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'3'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALLQ3

/*  --------------------------------------- VALOR LIQUIDO 3 --------------------------------*/

,	
/*  --------------------------------------- VALOR LIQUIDO 4 --------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST((MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) - ( MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) * 
	CAST(SUM(CAST(VLBOLSADESCONTO AS NUMERIC (15,2))/100) AS NUMERIC (15,2)))) AS NUMERIC (15,2)) 'VALOR_LIQUIDO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'4'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALLQ4

/*  --------------------------------------- VALOR LIQUIDO 4 --------------------------------*/

,	
/*  --------------------------------------- VALOR LIQUIDO 5 --------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST((MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) - ( MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) * 
	CAST(SUM(CAST(VLBOLSADESCONTO AS NUMERIC (15,2))/100) AS NUMERIC (15,2)))) AS NUMERIC (15,2)) 'VALOR_LIQUIDO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'5'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALLQ5

/*  --------------------------------------- VALOR LIQUIDO 5 --------------------------------*/

,	
/*  --------------------------------------- VALOR LIQUIDO 6 --------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST((MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) - ( MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) * 
	CAST(SUM(CAST(VLBOLSADESCONTO AS NUMERIC (15,2))/100) AS NUMERIC (15,2)))) AS NUMERIC (15,2)) 'VALOR_LIQUIDO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'6'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALLQ6

/*  --------------------------------------- VALOR LIQUIDO 6 --------------------------------*/

,	
/*  --------------------------------------- VALOR LIQUIDO 7 --------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST((MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) - ( MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) * 
	CAST(SUM(CAST(VLBOLSADESCONTO AS NUMERIC (15,2))/100) AS NUMERIC (15,2)))) AS NUMERIC (15,2)) 'VALOR_LIQUIDO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'7'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALLQ7

/*  --------------------------------------- VALOR LIQUIDO 7 --------------------------------*/

,	
/*  --------------------------------------- VALOR LIQUIDO 8 --------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST((MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) - ( MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) * 
	CAST(SUM(CAST(VLBOLSADESCONTO AS NUMERIC (15,2))/100) AS NUMERIC (15,2)))) AS NUMERIC (15,2)) 'VALOR_LIQUIDO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'8'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALLQ8

/*  --------------------------------------- VALOR LIQUIDO 8 --------------------------------*/

,	
/*  --------------------------------------- VALOR LIQUIDO 9 --------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST((MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) - ( MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) * 
	CAST(SUM(CAST(VLBOLSADESCONTO AS NUMERIC (15,2))/100) AS NUMERIC (15,2)))) AS NUMERIC (15,2)) 'VALOR_LIQUIDO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'9'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALLQ9

/*  --------------------------------------- VALOR LIQUIDO 9 --------------------------------*/

,	
/*  --------------------------------------- VALOR LIQUIDO 10 --------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST((MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) - ( MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) * 
	CAST(SUM(CAST(VLBOLSADESCONTO AS NUMERIC (15,2))/100) AS NUMERIC (15,2)))) AS NUMERIC (15,2)) 'VALOR_LIQUIDO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'10'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALLQ10

/*  --------------------------------------- VALOR LIQUIDO 10 --------------------------------*/

,	
/*  --------------------------------------- VALOR LIQUIDO 11 --------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST((MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) - ( MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) * 
	CAST(SUM(CAST(VLBOLSADESCONTO AS NUMERIC (15,2))/100) AS NUMERIC (15,2)))) AS NUMERIC (15,2)) 'VALOR_LIQUIDO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'11'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALLQ11

/*  --------------------------------------- VALOR LIQUIDO 11 --------------------------------*/

,	
/*  --------------------------------------- VALOR LIQUIDO 12 --------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST((MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) - ( MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) * 
	CAST(SUM(CAST(VLBOLSADESCONTO AS NUMERIC (15,2))/100) AS NUMERIC (15,2)))) AS NUMERIC (15,2)) 'VALOR_LIQUIDO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'12'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALLQ12

/*  --------------------------------------- VALOR LIQUIDO 12 --------------------------------*/

,	
/*  --------------------------------------- VALOR LIQUIDO 13 --------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST((MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) - ( MAX(CAST(VALOR_PARCELA AS NUMERIC (15,2))) * 
	CAST(SUM(CAST(VLBOLSADESCONTO AS NUMERIC (15,2))/100) AS NUMERIC (15,2)))) AS NUMERIC (15,2)) 'VALOR_LIQUIDO'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'13'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALLQ13

/*  --------------------------------------- VALOR LIQUIDO 13 --------------------------------*/
,
	/*  --------------------------------------- VALOR BRUTO 2--------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST(VALOR.VALOR_PARCELA AS NUMERIC (15,2)) 'VALB'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'2'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALB2

/*  --------------------------------------- VALOR BRUTO 2--------------------------------*/

,
	/*  --------------------------------------- VALOR BRUTO 3--------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST(VALOR.VALOR_PARCELA AS NUMERIC (15,2)) 'VALB'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'3'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALB3

/*  --------------------------------------- VALOR BRUTO 3--------------------------------*/

,
	/*  --------------------------------------- VALOR BRUTO 4--------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST(VALOR.VALOR_PARCELA AS NUMERIC (15,2)) 'VALB'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'4'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALB4

/*  --------------------------------------- VALOR BRUTO 4--------------------------------*/

,
	/*  --------------------------------------- VALOR BRUTO 5--------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST(VALOR.VALOR_PARCELA AS NUMERIC (15,2)) 'VALB'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'5'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALB5

/*  --------------------------------------- VALOR BRUTO 5--------------------------------*/

,
	/*  --------------------------------------- VALOR BRUTO 6--------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST(VALOR.VALOR_PARCELA AS NUMERIC (15,2)) 'VALB'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'6'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALB6

/*  --------------------------------------- VALOR BRUTO 6--------------------------------*/

,
	/*  --------------------------------------- VALOR BRUTO 7--------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST(VALOR.VALOR_PARCELA AS NUMERIC (15,2)) 'VALB'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'7'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALB7

/*  --------------------------------------- VALOR BRUTO 7--------------------------------*/

,
	/*  --------------------------------------- VALOR BRUTO 8--------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST(VALOR.VALOR_PARCELA AS NUMERIC (15,2)) 'VALB'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'8'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALB8

/*  --------------------------------------- VALOR BRUTO 8--------------------------------*/

,
	/*  --------------------------------------- VALOR BRUTO 9--------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST(VALOR.VALOR_PARCELA AS NUMERIC (15,2)) 'VALB'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'9'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALB9

/*  --------------------------------------- VALOR BRUTO 9--------------------------------*/

,
	/*  --------------------------------------- VALOR BRUTO 10--------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST(VALOR.VALOR_PARCELA AS NUMERIC (15,2)) 'VALB'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'10'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALB10

/*  --------------------------------------- VALOR BRUTO 10--------------------------------*/

,
	/*  --------------------------------------- VALOR BRUTO 11--------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST(VALOR.VALOR_PARCELA AS NUMERIC (15,2)) 'VALB'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'11'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALB11

/*  --------------------------------------- VALOR BRUTO 11--------------------------------*/

,
	/*  --------------------------------------- VALOR BRUTO 12--------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST(VALOR.VALOR_PARCELA AS NUMERIC (15,2)) 'VALB'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'12'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALB12

/*  --------------------------------------- VALOR BRUTO 12--------------------------------*/

,
	/*  --------------------------------------- VALOR BRUTO 13--------------------------------*/
ISNULL(
CONVERT(VARCHAR(255),
(
SELECT
	CAST(VALOR.VALOR_PARCELA AS NUMERIC (15,2)) 'VALB'
FROM
	BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS VW
WHERE
	VW.RA					=	C.RA
AND VW.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
AND VW.CODCOLIGADA			=	C.CODCOLIGADA
AND VW.IDPERLET				=	C.IDPERLET
AND VW.CODCONTRATO			=	C.CODCONTRATO
AND VW.PARCELA				=	'13'
--GROUP BY VW.RA,VW.IDHABILITACAOFILIAL,VW.CODCOLIGADA,VW.IDPERLET,VW.CODCONTRATO,VW.PARCELA
)),'--X--X--') VALB13

/*  --------------------------------------- VALOR BRUTO 13--------------------------------*/

FROM
	BD20200619_DSV.dbo.SCONTRATO C ( NOLOCK )						INNER JOIN  BD20200619_DSV.dbo.VW_ZZ_ALUNO_BOLSA_TIPOS					VALOR	( NOLOCK )	ON
									C.RA					=	VALOR.RA
								AND C.IDPERLET				=	VALOR.IDPERLET
								AND C.IDHABILITACAOFILIAL	=	VALOR.IDHABILITACAOFILIAL
								AND C.CODCOLIGADA			=	VALOR.CODCOLIGADA
								AND C.CODCONTRATO			=	VALOR.CODCONTRATO
																	INNER JOIN	BD20200619_DSV.dbo.VW_ZZ_ALUNO_CONTRATO						CT	( NOLOCK )		ON
									CT.CODCOLIGADA			=	C.CODCOLIGADA
								AND CT.IDHABILITACAOFILIAL	=	C.IDHABILITACAOFILIAL
								AND CT.IDPERLET				=	C.IDPERLET
								AND CT.RA					=	C.RA
								AND	CT.CODCONTRATO			=	C.CODCONTRATO	
												INNER JOIN	INTEGRA_RMK.dbo.DOCU_ENVELOPE													EN		( NOLOCK )	ON
							VALOR.RA					=	EN.TOTVS_RA
						AND VALOR.IDPERLET				=	EN.TOTVS_IDPERLET
						AND VALOR.IDHABILITACAOFILIAL	=	EN.TOTVS_IDHABILITACAOFILIAL
						AND VALOR.CODCOLIGADA			=	EN.TOTVS_CODCOLIGADA
						AND VALOR.CODCONTRATO			=	EN.TOTVS_CODCONTRATO
												INNER JOIN	INTEGRA_RMK.dbo.DOCU_ENVELOPE_STATUS											ST		( NOLOCK )	ON
							EN.DOCU_IDENVELOPE		=	ST.DOCU_IDENVELOPE			
WHERE
	ST.DOCU_STATUS			=	'completed'
AND C.RA					=	'12016903'
AND C.CODCOLIGADA			=	'1'
AND C.CODCONTRATO			=	'34259'
--AND	C.STATUS				=	'N'
--AND C.DTASSINATURA			IS NULL
--GROUP BY C.RA,C.IDHABILITACAOFILIAL,C.CODCOLIGADA,C.IDPERLET,C.CODCONTRATO,VALOR.PARCELA,CT.CPFRESPFIN,CT.RESPFIN_CPF,CT.RGRESPFIN,VALOR.ALUNO,VALOR.ANO_LETIVO

--PARCELA, IDPARCELA, C.RA                  
    '''
    db_docu.select_sql(db_docu.select)
    for rows in db_docu.rows:
        row = rows.rstrip()
        arrRow = row.split(",")
        VALB.append(arrRow[0].replace('.',','))
        RA_AD.append(arrRow[1])
        IDHABILITACAOFILIAL_AD.append(arrRow[2])
        CODCOLIGADA_AD.append(arrRow[3])
        IDPERLET_AD.append(arrRow[4])
        CODCONTRATO_AD.append(arrRow[5])
        NOME_AD.append(arrRow[6])
        ANOLETIVO_AD.append(arrRow[7])
        RESP_AD.append(arrRow[8])
        CPF_AD.append(arrRow[9])
        RG_AD.append(arrRow[10])
        UNIDADE_AD.append(arrRow[11])
        CURSO_AD.append(arrRow[12])
        BOLSA1.append(arrRow[13])
        BOLSA2.append(arrRow[14])
        BOLSA3.append(arrRow[15])
        BOLSA4.append(arrRow[16])
        BOLSA5.append(arrRow[17])
        BOLSA6.append(arrRow[18])
        BOLSA7.append(arrRow[19])
        BOLSA8.append(arrRow[20])
        BOLSA9.append(arrRow[21])
        BOLSA10.append(arrRow[22])
        BOLSA11.append(arrRow[23])
        BOLSA12.append(arrRow[24])
        BOLSA13.append(arrRow[25])
        VALDESC1.append(arrRow[26].replace('.',','))
        VALDESC2.append(arrRow[27].replace('.',','))
        VALDESC3.append(arrRow[28].replace('.',','))
        VALDESC4.append(arrRow[29].replace('.',','))
        VALDESC5.append(arrRow[30].replace('.',','))
        VALDESC6.append(arrRow[31].replace('.',','))
        VALDESC7.append(arrRow[32].replace('.',','))
        VALDESC8.append(arrRow[33].replace('.',','))
        VALDESC9.append(arrRow[34].replace('.',','))
        VALDESC10.append(arrRow[35].replace('.',','))
        VALDESC11.append(arrRow[36].replace('.',','))
        VALDESC12.append(arrRow[37].replace('.',','))
        VALDESC13.append(arrRow[38].replace('.',','))
        VALLQ1.append(arrRow[39].replace('.',','))
        VALLQ2.append(arrRow[40].replace('.',','))
        VALLQ3.append(arrRow[41].replace('.',','))
        VALLQ4.append(arrRow[42].replace('.',','))
        VALLQ5.append(arrRow[43].replace('.',','))
        VALLQ6.append(arrRow[44].replace('.',','))
        VALLQ7.append(arrRow[45].replace('.',','))
        VALLQ8.append(arrRow[46].replace('.',','))
        VALLQ9.append(arrRow[47].replace('.',','))
        VALLQ10.append(arrRow[48].replace('.',','))
        VALLQ11.append(arrRow[49].replace('.',','))
        VALLQ12.append(arrRow[50].replace('.',','))
        VALLQ13.append(arrRow[51].replace('.',','))
        VALB2.append(arrRow[52].replace('.',','))
        VALB3.append(arrRow[53].replace('.',','))
        VALB4.append(arrRow[54].replace('.',','))
        VALB5.append(arrRow[55].replace('.',','))
        VALB6.append(arrRow[56].replace('.',','))
        VALB7.append(arrRow[57].replace('.',','))
        VALB8.append(arrRow[58].replace('.',','))
        VALB9.append(arrRow[59].replace('.',','))
        VALB10.append(arrRow[60].replace('.',','))
        VALB11.append(arrRow[61].replace('.',','))
        VALB12.append(arrRow[62].replace('.',','))
        VALB13.append(arrRow[63].replace('.',','))        
        print(arrRow)
        print(CPF_AD[0])
        print(UNIDADE_AD[0])
        print(VALDESC1[0])
start_variables_template_aditivo()


