import db_docu

db_docu.select = '''SELECT 
	VW.CIDADE_ALUNO		[CIDADE]
,   PP.CARTIDENTIDADE	[RG]
,	VW.ALUNO			[NOMEALUNO]
,	VW.UNIDADE
,	VW.SEXO
,	VW.NATURALIDADE		[LOCALNASC]
,	VW.RESPFIN			[NOMERESPF]
,	VW.ENDERECORESPFIN	[ENDERECO]
,	VW.NOME_CURSO		[CURSO]
,	VW.CEP_ALUNO		[CEP]
,	VW.NOME_SERIE		[SEIRE]
,	VW.PERIODO
,	VW.NATURALIDADE		
,	CONVERT(VARCHAR(10),PP.DTNASCIMENTO,103)		[DATANASC]
,	VW.RESPFIN_TEL		[TELR]
,	VW.TEL1_ALUNO		[TELC]
,	VW.ESTADONATAL		[UF]
,	VW.BAIRRO_ALUNO		[BAIRRO]
,	VW.NOME_PAI			[PAI]
,	VW.NOME_MAE			[MAE]
,	CT.RA
FROM
	BD20200619_DSV.DBO.SCONTRATO CT INNER JOIN BD20200619_DSV.dbo.VW_ZZ_ALUNO_CONTRATO VW	ON
									CT.CODCOLIGADA			=	VW.CODCOLIGADA
								AND CT.IDHABILITACAOFILIAL	=	VW.IDHABILITACAOFILIAL
								AND CT.IDPERLET				=	VW.IDPERLET
								AND CT.RA					=	VW.RA
								AND	CT.CODCONTRATO			=	VW.CODCONTRATO
									INNER JOIN BD20200619_DSV.dbo.PPESSOA PP				ON
									VW.CODPESSOA			=	PP.CODIGO
WHERE
	CT.CODCONTRATO			=	'34208'
AND CT.RA					=	'18013107'
AND CT.IDPERLET				=	'44'
AND CT.IDHABILITACAOFILIAL	=	'725'
                    '''
db_docu.select_sql(db_docu.select)
